"""Add achievement and streak tables

Revision ID: d9c463fd7ffc
Revises: a8d14e08a8f6
Create Date: 2026-01-28 22:47:51.897925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9c463fd7ffc'
down_revision: Union[str, Sequence[str], None] = 'a8d14e08a8f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
